"""Serve the built React application without intercepting backend routes."""

from pathlib import Path

from flask import Blueprint, abort, current_app, send_from_directory


frontend_bp = Blueprint("frontend", __name__)


def _dist_directory() -> Path:
    return Path(current_app.config["FRONTEND_DIST_DIR"])


def serve_react_app():
    """Return Vite's generated entry document for one React-owned route."""

    dist_directory = _dist_directory()
    index_file = dist_directory / "index.html"
    if not index_file.is_file():
        return (
            "CareerGrid's frontend build is unavailable. "
            "Run `npm run build` in the frontend directory.",
            503,
        )
    return send_from_directory(dist_directory, "index.html")


@frontend_bp.get("/assets/<path:filename>")
def vite_asset(filename):
    """Serve fingerprinted files generated by Vite."""

    return send_from_directory(_dist_directory() / "assets", filename)


@frontend_bp.get("/<path:path>")
def spa_fallback(path):
    """Support React Router refreshes while preserving backend 404 behavior."""

    first_segment = path.partition("/")[0]
    if first_segment in {"api", "assets", "static"}:
        abort(404)
    return serve_react_app()
