import { useState } from 'react'

function TerminalApp({ files, git, onGit }) {
  const [input, setInput] = useState('')
  const [history, setHistory] = useState([])
  const run = (event) => { event.preventDefault(); const command = input.trim(); if (!command) return; const target = command.slice(4); const output = command === 'pwd' ? '/Projects' : command === 'ls' ? files.map((file) => file.path.split('/').pop()).join('  ') : command.startsWith('cd ') ? (target === '..' || target === '/Projects' ? '' : `cd: ${target}: No such file or directory`) : command.startsWith('cat ') ? files.find((file) => file.path === target || file.path.endsWith(`/${target}`))?.content || `cat: ${target}: No such file` : command === 'git status' ? (git.modified.length ? `On branch ${git.branch}\nChanges not staged for commit:\n${git.modified.map((path) => `  modified: ${path}`).join('\n')}` : `On branch ${git.branch}\nnothing to commit, working tree clean`) : command === 'git branch' ? `* ${git.branch}` : command.startsWith('git switch -c ') || command.startsWith('git checkout -b ') ? onGit('branch', command.split(' ').at(-1)) : command.startsWith('git switch ') ? onGit('branch', command.slice(11)) : command === 'git add .' ? onGit('stage', git.modified) : command.startsWith('git add ') ? onGit('stage', [command.slice(8)]) : command.startsWith('git commit -m ') ? onGit('commit', command.match(/"(.*)"/)?.[1] || '') : command === 'git push' ? onGit('push') : command === 'help' ? 'Available commands: pwd, ls, cd, cat, git status, git branch, git switch, git add, git commit, git push, clear' : command === 'clear' ? '__CLEAR__' : `${command}: command not found`; setHistory((items) => output === '__CLEAR__' ? [] : [...items, { command, output: output || `Switched directory to ${target}` }]); setInput('') }
  return <><div className="terminal-tab-bar"><div className="terminal-tab is-active">&gt;_ bash</div><div className="terminal-working-directory">/Projects</div></div><div className="terminal-screen"><div className="terminal-welcome">CareerGrid Workspace Terminal<br />Type <strong>help</strong> to see available commands.</div><div className="terminal-history">{history.map((entry, index) => <div className="terminal-command-block" key={index}><div>careergrid:~/Projects$ {entry.command}</div><pre>{entry.output}</pre></div>)}</div></div><form className="terminal-command-bar" onSubmit={run}><span className="terminal-prompt">careergrid:~/Projects$</span><input className="terminal-input" value={input} onChange={(event) => setInput(event.target.value)} autoFocus /></form></>
}

export default TerminalApp
