function slug(value) { return String(value || 'repository').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'repository' }
function copy(value) { return JSON.parse(JSON.stringify(value)) }
function snapshot(files) { return Object.fromEntries(files.map((file) => [file.path, copy(file)])) }

function createRepository(files = [], { path = '/Projects/careergrid-workspace', name = 'careergrid-workspace' } = {}) {
  const tree = snapshot(files)
  const initial = { id: 'initial', message: 'Initial workspace', author: 'CareerGrid User', createdAt: new Date().toISOString(), snapshot: copy(tree) }
  return { rootPath: path, repositoryName: name, repositorySlug: slug(name), defaultBranch: 'main', currentBranch: 'main', branches: { main: { commits: [initial], headSnapshot: copy(tree), workingTree: copy(tree), stagedPaths: [] } }, remote: { pushedBranches: [], branchHeads: {} }, pullRequests: [], submissions: {}, submissionCandidates: {}, evaluations: {} }
}
function changedFiles(repository) { const branch = repository.branches[repository.currentBranch]; return Object.keys(branch.workingTree).filter((path) => !branch.headSnapshot[path] || branch.headSnapshot[path].content !== branch.workingTree[path].content) }
function saveFile(repository, path, content) { const next = copy(repository); const branch = next.branches[next.currentBranch]; if (!branch.workingTree[path]) return { repository: next, error: 'File not found.' }; branch.workingTree[path].content = content; return { repository: next } }
function createBranch(repository, branchName) { const next = copy(repository); if (!branchName || next.branches[branchName]) return { repository: next, error: 'Branch already exists or is invalid.' }; const source = next.branches[next.currentBranch]; next.branches[branchName] = { commits: copy(source.commits), headSnapshot: copy(source.headSnapshot), workingTree: copy(source.workingTree), stagedPaths: [] }; next.currentBranch = branchName; return { repository: next } }
function switchBranch(repository, branchName) { const next = copy(repository); if (!next.branches[branchName]) return { repository: next, error: 'Branch not found.' }; next.currentBranch = branchName; return { repository: next } }
function stage(repository, paths) { const next = copy(repository); const branch = next.branches[next.currentBranch]; const changed = changedFiles(next); const requested = paths === '.' ? changed : paths; branch.stagedPaths = [...new Set([...branch.stagedPaths, ...requested.filter((path) => changed.includes(path))])]; return { repository: next } }
function commit(repository, message) { const next = copy(repository); const branch = next.branches[next.currentBranch]; if (!message || !branch.stagedPaths.length) return { repository: next, error: !message ? 'Commit message required.' : 'No staged changes.' }; const record = { id: `${Date.now().toString(36)}`, message, author: 'CareerGrid User', createdAt: new Date().toISOString(), snapshot: copy(branch.workingTree) }; branch.commits.push(record); branch.headSnapshot = copy(branch.workingTree); branch.stagedPaths = []; return { repository: next, commit: record } }
function push(repository) { const next = copy(repository); const branch = next.currentBranch; if (!next.remote.pushedBranches.includes(branch)) next.remote.pushedBranches.push(branch); next.remote.branchHeads[branch] = next.branches[branch].commits.at(-1)?.id; return { repository: next } }
function createPullRequest(repository, details) { const next = copy(repository); const { baseBranch, compareBranch, title, description = '' } = details; if (!next.branches[baseBranch] || !next.branches[compareBranch]) return { repository: next, error: 'Select branches that exist in this repository.' }; if (baseBranch === compareBranch || compareBranch === 'main') return { repository: next, error: 'Choose a feature branch to compare with main.' }; if (!next.remote.pushedBranches.includes(compareBranch)) return { repository: next, error: 'Push this branch before opening a pull request.' }; const baseIds = new Set(next.branches[baseBranch].commits.map((item) => item.id)); if (!next.branches[compareBranch].commits.some((item) => !baseIds.has(item.id))) return { repository: next, error: 'This branch has no commits to compare with the base branch.' }; if (!title?.trim()) return { repository: next, error: 'Add a pull request title.' }; const id = Math.max(0, ...next.pullRequests.map((item) => Number(item.id) || 0)) + 1; const pullRequest = { id, repositoryPath: next.rootPath, repositoryName: next.repositoryName, repositorySlug: next.repositorySlug, baseBranch, compareBranch, title: title.trim(), description: description.trim(), author: 'CareerGrid User', createdAt: new Date().toISOString(), status: 'open', url: `https://github.com/careergrid-sim/${next.repositorySlug}/pull/${id}` }; next.pullRequests.push(pullRequest); return { repository: next, pullRequest } }
export { changedFiles, commit, createBranch, createPullRequest, createRepository, push, saveFile, stage, switchBranch }
